project_name: coolshell

builds:
  - <<: &build_defaults
      env:
        - CGO_ENABLED=0
      ldflags:
        - -w -s
    id: macos
    goos: [ darwin ]
    goarch: [ amd64, arm64 ]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: [amd64, arm64]

dockers:

  - image_templates:
      - "soulteary/forever-coolshell:linux-amd64-{{ .Tag }}"
      - "soulteary/forever-coolshell:linux-amd64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/forever-coolshell"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/forever-coolshell"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  - image_templates:
      - "soulteary/forever-coolshell:linux-arm64-{{ .Tag }}"
      - "soulteary/forever-coolshell:linux-arm64"
    dockerfile: docker/Dockerfile.gorelease
    use: buildx
    goos: linux
    goarch: arm64
    goarm: ''
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }}"
      - "--label=org.opencontainers.image.url=https://github.com/soulteary/forever-coolshell"
      - "--label=org.opencontainers.image.source=https://github.com/soulteary/forever-coolshell"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  - name_template: "soulteary/forever-coolshell:{{ .Tag }}"
    image_templates:
      - "soulteary/forever-coolshell:linux-amd64-{{ .Tag }}"
      - "soulteary/forever-coolshell:linux-arm64-{{ .Tag }}"
    skip_push: "false"

  - name_template: "soulteary/forever-coolshell:latest"
    image_templates:
      - "soulteary/forever-coolshell:linux-amd64-{{ .Tag }}"
      - "soulteary/forever-coolshell:linux-arm64-{{ .Tag }}"
    skip_push: "false"